linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
    settings:
      hugeParam:
        sizeThreshold: 96
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  presets:
    - bugs
    - unused
    - performance
    - format
    - metalinter
  enable:
    - goerr113
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - stylecheck
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goerr113
        - noctx
    - path: _test\.go
      text: fieldalignment
    - path: _test\.go
      text: Using the variable on range scope `tt` in function literal
  max-per-linter: 0
  max-same: 0
